[package]
name = "cano-ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
cano-types = { path = "../cano-types" }
cano-crypto = { path = "../cano-crypto" }
cano-wire  = { path = "../cano-wire" }
cano-serde = { path = "../cano-serde" }
cano-hash  = { path = "../cano-hash" }